-- require('packer-plugin')
require('user/options')
require('user/keymap')
require('user/plugin')
require('user/cmp')
require('user/lsp')
require('user/mason')
require('user/telescope')
require('user/treesitter')
require('user/gitsigns')
require('user/nvimtree')
